[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = "."
markers = [
    "pubsub: tests that require pubsub emulator",
]

[tool.mypy]
python_version = "3.12"
ignore_missing_imports = true
disable_error_code = "annotation-unchecked"

[tool.isort]
profile = "black"
